default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inventory_manager_development

test:
  <<: *default
  database: inventory_manager_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
